In [ ]:
import pandas as pd
import numpy as np

In [ ]:
days=list(range(1,11))
news_type=[0 for i in range(10)]
d=[0 for i in range(10)]
rvs=[0 for i in range(10)]
lost_profit=[0 for i in range(10)]
salvage=[0 for i in range(10)]
daily_profit=[0 for i in range(10)]
rn_nt=[86,32,73,24,76,38,45,18,44,12]
rn_demand=[4,39,66,89,97,24,9,55,15,17]
Cost_of_NPs=70*0.33

In [ ]:
def rn_nt_func(rn):
    if rn>=1 and rn<=35:
        return "good"
    elif rn>=36 and rn<=80:
        return "fair" 
    elif (rn>=81 and rn<=99) or rn==0 :
        return "poor"
def rn_d(rn,ntype):
  if ntype=="good":
    if rn>=1 and rn<=3:
        return 40
    elif rn>=4 and rn<=8:
        return 50
    elif rn>=9 and rn<=23:
        return 60
    elif rn>=24 and rn<=43:
        return 70
    elif rn>=44 and rn<=78:
        return 80
    elif rn>=79 and rn<=93:
        return 90
    elif rn==0 or (rn>=94 and rn<=99 ):
        return 100
  if ntype=="fair":
    if rn>=1 and rn<=10:
        return 40
    elif rn>=11 and rn<=28:
        return 50
    elif rn>=29 and rn<=68:
        return 60
    elif rn>=69 and rn<=88:
        return 70
    elif rn>=89 and rn<=96:
        return 80
    elif rn==0 or (rn>=97 and rn<=99 ):
        return 90
  if ntype=="poor":
    if rn>=1 and rn<=44:
        return 40
    elif rn>=45 and rn<=66:
        return 50
    elif rn>=67 and rn<=82:
        return 60
    elif rn>=83 and rn<=94:
        return 70
    elif rn==0 or (rn>=95 and rn<=99 ):
        return 80

In [ ]:
for i in range(10):
  news_type[i]=rn_nt_func(rn_nt[i])
  d[i]=rn_d(rn_demand[i],news_type[i])
  if d[i]<70:
    rvs[i]=d[i]*0.50
    salvage[i]=(70-d[i])*0.05
    lost_profit[i]="-"
    daily_profit[i]=(rvs[i]+salvage[i])-Cost_of_NPs
  if d[i]>70:
    rvs[i]=70*0.50
    salvage[i]="-"
    lost_profit[i]=(d[i]-70)*0.17
    daily_profit[i]=(rvs[i]-lost_profit[i])-Cost_of_NPs
  if d[i]==70:
    rvs[i]=70*0.50
    salvage[i]="-"
    lost_profit[i]="-"
    daily_profit[i]=(rvs[i])-Cost_of_NPs

df={"days":days,"random num(type)":rn_nt,"news type":news_type,"rn for damand":rn_demand,"demand":d,"revenue from sales":rvs,"lost profit":lost_profit,"scrap":salvage,"dialy profit":daily_profit}
        
df=pd.DataFrame(df)
df.index = np.arange(1, len(df)+1)

In [ ]:
df

,days,random num(type),news type,rn for damand,demand,revenue from sales,lost profit,scrap,dialy profit
1,1,86,poor,4,40,20.0,-,1.5,-1.6
2,2,32,good,39,70,35.0,-,-,11.9
3,3,73,fair,66,60,30.0,-,0.5,7.4
4,4,24,good,89,90,35.0,3.4,-,8.5
5,5,76,fair,97,90,35.0,3.4,-,8.5
6,6,38,fair,24,50,25.0,-,1.0,2.9
7,7,45,fair,9,40,20.0,-,1.5,-1.6
8,8,18,good,55,80,35.0,1.7,-,10.2
9,9,44,fair,15,50,25.0,-,1.0,2.9
10,10,12,good,17,60,30.0,-,0.5,7.4